export const CART_REDUCER_TYPES = {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    TOTAL_ITEMS_IN_CART: 'TOTAL_ITEMS_IN_CART',
    SET_OVERALL_PRICE: 'SET_OVERALL_PRICE',
    SET_CART_OPEN: 'SET_CART_OPEN'
}


